baseURL = 'http://example.org/'
languageCode = 'ja'
title = 'ものコン-wiki'
theme = 'hugo-theme-relearn'

defaultContentLanguage = "ja"
hasCJKLanguage = true

[params]
author = "KATO Jinnosuke"
description = "ものづくりコンテストについての情報をまとめたWikiです"
collapsibleMenu = true

[[menu.shortcuts]]
name = "<i class='fa-regular fa-link'></i> ものコン公式サイト"
url = "http://zenkoukyo.or.jp/index_contest/mono_index/"
weight = 40
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> タグ一覧"
url = "/tags"
weight = 30

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = false